### ISSUE TITLE
Change #!/bin.sh to #!/bin/sh

### ISSUE THREAD

**Issue by Nighttraveler** [Quacky2200/Spotify-Web-Player-for-Linux#10]
Hi guys
I install your app from the releases versions (amd64) and i have to change #!/bin.sh to #!/bin/sh in the spotifywebplayer file and  sudo chmod +x  and then it run fine.
Thaks for your app!

**Comment by Quacky2200** [comment]
Yeah I see it, can't believe I didn't see that. Currently I cannot sync or upload a new package just yet. I will leave this open as a reminder and thanks for telling me

**Comment by Quacky2200** [comment]
Fixed: https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/commit/fc1360978fd128c5d23633ad99543b65648b732a
