### ISSUE TITLE
Toggle menu bar

### ISSUE THREAD

**Issue by imnofox** [Quacky2200/Spotify-Web-Player-for-Linux#12]
Would be great if I could toggle the menu bar.

It can really look out of place, and is often not needed to be shown. :smile:

**Comment by Quacky2200** [comment]
Yes, this is something I have thought about when I was testing it out on Debian. I will add it to a TODO list

**Comment by Quacky2200** [comment]
Added in https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/tag/1.0.0

**Comment by amarktl** [comment]
Hi, 
I installed the player using your manual installation guide on my Fedora 25 w/ Cinnamon Desktop machine. The player is working fine but i do not have a tray icon and i have no idea how to show the application menu bar to be able to change some preferences. 
Would be great if you can point me in the right direction. :)

BR,
Alex

**Comment by Quacky2200** [comment]
I'm not sure why it would suddenly appear either, it could perhaps be due to authentication and how fast the page loads but I've never had that problem before. With the tray icon you need to make sure you have libappindicator installed.

**Comment by amarktl** [comment]
Hi, 

After restarting the system everything is working fine. I had an other spotify player installed as well and i think it might have caused some conflicts. 

Thanks you and keep up the good work :)

BR,
Alex
