### ISSUE TITLE
Install instructions for Fedora

### ISSUE THREAD

**Issue by JasonLG1979** [Quacky2200/Spotify-Web-Player-for-Linux#13]
Just wondering if anyone knows off hand how to install on Fedora? I tried the Ubuntu instructions in the readme minus the apt-get parts ofc(I already have libappindicator1, libnotify4, wget, unzip installed) and it fails spectacularly,lol!!!

**Comment by Quacky2200** [comment]
I have recently removed the node_modules folder as they now need to be built for each architecture (a follow up README.md needs to occur), so technically to be able to install you need Node.JS and some build libraries, from the top of my head, the packages used for Ubuntu are: 
libexpat
libdbus-1-dev
libglib2.0-dev
build-essentials
Node.JS /NPM /node-gyp 

Of course you just need to be able to find the packages for Fedora. You then need to 'npm install' the Spotify directory to install all of the essential package dependencies. Since implementing a range of things, I never allowed the dbus_service to run without a local prerequisite version of Node.JS. 

This means you can either download the prerequisites and keep everything together, or you make a link between your version of node and refer it to /path/to/project/libs/node/bin/node. At this point on you have started using it more as a developer than a user, but that's the 'easy way' to install it at this time.

**Comment by JasonLG1979** [comment]
That looks like a job for my next day off,lol!!! when I figure it out I'll post step by step instructions and/or make a wiki page for installing on Fedora.

**Comment by Quacky2200** [comment]
Try the edit I just posted it is quite simple, if that works, I will edit the README for the temporary solution until I create RPM packages

**Comment by JasonLG1979** [comment]
```bash
sudo mkdir -p /usr/bin/spotifywebplayer/lib/electron && sudo unzip master.zip /usr/bin/spotifywebplayer
```

Results in:
```bash
Archive:  master.zip
a238a4229acf102f6866e9bad77aa522c3665733
caution: filename not matched:  /usr/bin/spotifywebplayer
```

**Comment by Quacky2200** [comment]
Ahh sorry, try changing that to 
```
sudo mkdir -p /usr/bin/spotifywebplayer/lib/electron && sudo unzip master.zip -d /usr/bin/spotifywebplayer
```

**Comment by JasonLG1979** [comment]
> Ahh sorry, try changing that to

That worked butt...
```bash
cd /usr/bin/spotifywebplayer && . ./get_prerequisites.sh
```
Results in:
```bash
bash: ./get_prerequisites.sh: No such file or directory
```

**Comment by Quacky2200** [comment]
The seems odd as I have no problem with the command at all.... I can only suggest making sure the get_prerequisites.sh file exists in /usr/bin/spotifywebplayer

**Comment by Quacky2200** [comment]
Is there a folder called master inside the /usr/bin/spotifywebplayer directory?

**Comment by JasonLG1979** [comment]
Yep.

```bash
cd /usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master && ./get_prerequisites.sh
```
Finds and runs the script but results in:
```bash
Extracting Electron...
Archive:  /tmp/tmp.hNv3hewGbr
checkdir:  cannot create extraction directory: /usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master/libs//electron
           No such file or directory
Renamed Electron for process name similarity
mv: cannot stat '/usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master/libs//electron/electron': No such file or directory
Extracting Node.JS
tar: /usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master/libs: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat '/usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master/libs//node*': No such file or directory
Finished! :)
```
My guess would be the double "\"'s  ("/libs//node")

**Comment by Quacky2200** [comment]
nah it's because you previously created the libs and electron directory with the command
```
mkdir -p /usr/bin/spotifywebplayer/libs/electron
```
so when the zip had extracted to the wrong place (my mistake :S) the libs folder doesn't exist. The best thing to do would be to move everything out of the /usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master into /usr/bin/spotifywebplayer and run the get_prerequisites.sh script again, perhaps something like...
```
cp -R /usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master/* /usr/bin/spotifywebplayer
```

**Comment by JasonLG1979** [comment]
Tried:
```bash
sudo cp -R /usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master/* /usr/bin/spotifywebplayer
```

And then:
```bash
cd /usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master && ./get_prerequisites.sh
```

The result was the same.

**Comment by JasonLG1979** [comment]
Scratch that. My bad I got a permission denied.

That last command needs to be:
```bash
cd /usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master && sudo ./get_prerequisites.sh
```

**Comment by JasonLG1979** [comment]
The script seems to have finished with no errors.

**Comment by Quacky2200** [comment]
That's fine, but I would remove the Spotify-Web-Player-for-Linux-master as everything is now in /usr/bin/spotifywebplayer

```
rm -rf /usr/bin/spotifywebplayer/Spotify-Web-Player-for-Linux-master
```
You will then have to extract the node_modules to the right place (run the command if 64bit)
```
wget https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/files/458211/node_modules_x64.zip && unzip node_modules_x64.zip -d /usr/bin/spotifywebplayer
```
There's also an error with the last bit in the README as I have read on...
```
sudo cp /usr/bin/spotifywebplayer/icons/spotify-web-player.png /usr/share/pixmaps/spotify-web-player.png
```
Setup the launcher
```
sudo echo "[Desktop Entry]\nVersion=0.9.5-1\nName=Spotify Web Player\nComment=Music for every moment. Spotify is a digital music service that gives you access to millions of songs.\nExec=bash /usr/bin/spotifywebplayer/spotifywebplayer\nPath=/usr/bin/spotifywebplayer\nIcon=spotify-web-player\nCategories=GNOME;GTK;AudioVideo;Audio;Player;\nActions=PlayPause;Next;Previous;\nType=Application\nTerminal=false\n[Desktop Action PlayPause]\nName=Play/Pause\nExec=dbus-send --print-reply --reply-timeout=2500 --session --dest=org.mpris.MediaPlayer2.spotifywebplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause\n[Desktop Action Next]\nName=Next\nExec=dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotifywebplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next\n[Desktop Action Previous]\nName=Previous\nExec=dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotifywebplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous"
```

**Comment by Quacky2200** [comment]
You will also have to install libXScrnSaver using the command
```
dnf install libXScrnSaver
```
I don't know why but for some reason Electron requires it

**Comment by JasonLG1979** [comment]
It was already installed.

Your giant echo to create the desktop file fails. You should just ship a desktop file already made prob. I made my own based on your echo. mpris commands from the desktop file?

**Comment by Quacky2200** [comment]
Yeah I realised that it failed, it was missing the -e parameter. Once that is there it works :)

**Comment by JasonLG1979** [comment]
I get:
```bash
bash: /usr/share/applications/spotifywebplayer.desktop: Permission denied
```

**Comment by Quacky2200** [comment]
I'm not sure what command you're trying to do to that file, where it's chmod, echo etc, you will need to be root to modify the file (sudo?)

**Comment by JasonLG1979** [comment]
the echo

**Comment by JasonLG1979** [comment]
I'll try sudo su

**Comment by JasonLG1979** [comment]
sudo su did the trick for the echo. But now I get nothing when I click the icon.(no process is even started)

If I try the command from the desktop file I get:
```bash
/usr/bin/spotifywebplayer/./spotifywebplayer: line 4: /usr/bin/spotifywebplayer/libs/electron/spotifywebplayer: No such file or directory
```

**Comment by Quacky2200** [comment]
is the electron executable called spotifywebplayer? If it is then is would be located in /usr/bin/spotifywebplayer/libs/electron/spotifywebplayer

**Comment by JasonLG1979** [comment]
/usr/bin/spotifywebplayer/libs/electron/ is empty

**Comment by Quacky2200** [comment]
Oh, try running the prerequisite again, you ran it from the old directory, I wonder if that had any effect..
```
. /usr/bin/spotifywebplayer/get_prerequisites.sh
```
Other than that you will have to download electron manually

**Comment by JasonLG1979** [comment]
No bueno:

```bash
Extracting Electron...
Archive:  /tmp/tmp.VYc14HwqfX
checkdir:  cannot create extraction directory: /usr/bin/spotifywebplayer/libs//electron
           No such file or directory
Renamed Electron for process name similarity
mv: cannot stat '/usr/bin/spotifywebplayer/libs//electron/electron': No such file or directory
Extracting Node.JS
tar: /usr/bin/spotifywebplayer/libs: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat '/usr/bin/spotifywebplayer/libs//node*': No such file or directory
Finished! :)
```

**Comment by Quacky2200** [comment]
Run with root/sudo? I can't imagine it being the script as it has been fine or so long

**Comment by JasonLG1979** [comment]
``bash
cd /usr/bin/spotifywebplayer && sudo ./get_prerequisites.sh
```
Did the trick. It's up and running. Thanks!!!

**Comment by JasonLG1979** [comment]
Slightly off topic but is this normal?
![image](https://cloud.githubusercontent.com/assets/6667703/18300767/f18414e6-7491-11e6-9d7a-1b2215678d8d.png)


That seems like excessive resource usage.

**Comment by Quacky2200** [comment]
Sadly yes, this is what Electron uses, it's pretty heavy however, the only figures you need to read is just normal memory rather than resident?

**Comment by JasonLG1979** [comment]
I know. Even that is crazy high. For a frame of reference Pithos uses about 45MB of "normal memory." I guess it is what it is. The price of portability I guess,lol!!!

**Comment by Quacky2200** [comment]
Yes, I totally agree however this is just a web application, if I could do it without needing all these resources I would but if I were, I would also probably be programming it in Python. There is a pyspotify type application that uses sockets but each time I look at similar projects like that, Spotify is always one step ahead and they stop working for a while - not production level at all...

**Comment by JasonLG1979** [comment]
I feel your pain. Pithos relies on a api's that aren't public. It's a cat and mouse game. They change the api and break Pithos for a little bit then we figure out how to work around it.

**Comment by Quacky2200** [comment]
The idea here (despite being a resource hog) is so that if anything does get changed which is hopefully just visual it will stay unaffected. Of course anything dramatic will prevent any of it working, but that's why I warn on my README that it's unofficial. Considering how Spotify change and/or remove so much functionality, I won't be able to assure people that it's safe from their evil developers :S. What I can assure them though is that it is more stable than pySpotify and node-spotify-web which have had neverending problems with playback, playlists and authentication.
