### ISSUE TITLE
Inconsistent MPRIS behavior.   

### ISSUE THREAD

**Issue by JasonLG1979** [Quacky2200/Spotify-Web-Player-for-Linux#14]
I fully realize how much of a PITA MPRIS can be. But in the short time(mins) that I've been using Spotify-Web-Player-for-Linux I've noticed inconsistent MPRIS behavior. The album cover either doesn't change with the song or in some cases doesn't show up at all. The song info text some times changes with the song sometimes not.

**Comment by Quacky2200** [comment]
Yeah, it really is a pain, having to run two different processes just to handle D-Bus messages and also having Spotify sending multiple events it can be hard to interpret, I am working on this though.

**Comment by JasonLG1979** [comment]
There's also the fact that no 2 "applet" interprets the spec the same so you'll have a half a dozen workarounds to make for consistent behavior between them.

**Comment by JasonLG1979** [comment]
You may want to throw "xesam:url" in your implementation. At least one MPRIS applet(https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer) uses that(wrongly IMHO) to determine the track has changed.

**Comment by JasonLG1979** [comment]
And I'm not sure about this:
```js
'mpris:trackid': player.objectPath('track/' + info.activeSong.id),
```
Your track id should look something like this(example from Pithos):
```python
"mpris:trackid": GLib.Variant('o', '/io/github/Pithos/TrackId/' + track_id),
```
Here's the spec:
https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Simple-Type:Track_Id

**Comment by Quacky2200** [comment]
Fixed in https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/tag/1.0.0
