### ISSUE TITLE
Close to sound-menu

### ISSUE THREAD

**Issue by wa4557** [Quacky2200/Spotify-Web-Player-for-Linux#16]
Since the player shows up in the soundmenu, would it be possible to disable the tray icon, and still closing the player to "tray" (i.e. soundmenu) and not minimizing it?

This is how the original spotify player behaves after all. 

P.S: Removing `spotify-ico-small.png` from `/usr/bin/spotifywebplayer/icons` does exactly that

**Comment by Quacky2200** [comment]
I originally didn't have this because not everyone has a sound menu, if they get their app stuck being hidden (because they don't have some kind of player menu); they would have to send a D-Bus raise command and I don't think people want that. I will still put it in - it will just need to have a good warning so I don't get issues :)

**Comment by JasonLG1979** [comment]
There are ways to detect MPRIS clients. It's kinda hacky sometimes. But in Ubuntu I believe there is a way to detect the sound menu by design just for such a reason.

Or you can just look for the soundmenu service with dbus. If you find the service you know you can minimize to the sound menu.

**Comment by JasonLG1979** [comment]
From indicator-sound_12.10.2+16.04.20160406/src/service.vala:
```vala
		/* Everything is built, let's put it on the bus */
		try {
			export_actions = bus.export_action_group ("/com/canonical/indicator/sound", this.actions);
		} catch (Error e) {
			critical ("%s", e.message);
		}

		this.menus.@foreach ( (profile, menu) => menu.export (bus, @"/com/canonical/indicator/sound/$profile"));
```

It appears all you'd have to do is look for the /com/canonical/indicator/sound interface maybe?

**Comment by Quacky2200** [comment]
Added in https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/tag/1.0.0
