### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Jimthetyreman** [Quacky2200/Spotify-Web-Player-for-Linux#17]
Open the app and it says "Connecting to Spotify" but stalls..............

Using Mint 17.3 Cinn DT.

**Comment by Quacky2200** [comment]
Restart the app, it should let you login - it's an annoying bug at the moment

**Comment by Quacky2200** [comment]
Should be fixed with https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/tag/1.0.0
