### ISSUE TITLE
Light theme not working properly

### ISSUE THREAD

**Issue by Alex99001** [Quacky2200/Spotify-Web-Player-for-Linux#18]
Hi,
I noticed that if I choose the light theme i cannot see the entirety of the playlist sidebar (see screenshot). It looks like it's cropped; i tried to scroll up but I can't go further. Basically, the "New Playlist" button is missing. Thank you.
![spotify screenshot](https://cloud.githubusercontent.com/assets/22057683/18320292/7e1e4240-7529-11e6-9230-570982c8c573.png)

**Comment by Quacky2200** [comment]
This should be solved in commit 6871f0b05bd16875d6bf257587d3220ae197f510 - as this is literally just one file changed, you can change the same file in /usr/bin/spotifywebplayer/js/preloaded/themes/light-theme.css and restart the application. 

This should be simple so until I have a significant amount of changes, this will not be put in a release alone.
