### ISSUE TITLE
Navigation buttons in window grayed out

### ISSUE THREAD

**Issue by karjaneth** [Quacky2200/Spotify-Web-Player-for-Linux#19]
Installed on Linux Mint 17.3 MATE using the spotifywebplayerv0.9.5-1-alpha-x64.deb file.
Logging in and playing works fine, but the left-hand side buttons for song navigation are grayed out, even while a song is playing.

![image](https://cloud.githubusercontent.com/assets/9848293/18320608/31196580-74f0-11e6-8fa4-324e3342bdcb.png)

**Comment by karjaneth** [comment]
Never mind, fully closed and opened it and it works now.

**Comment by Quacky2200** [comment]
Yes this is part of a login bug - it's quite annoying.. :/
