### ISSUE TITLE
Zombie process.

### ISSUE THREAD

**Issue by JasonLG1979** [Quacky2200/Spotify-Web-Player-for-Linux#27]
After quitting Spotify-Web-Player-for-Linux it leaves a zombie process(spotifywebplayer) that either has to be killed manually or by clicking on the Spotify icon in the sound indicator.

In Xubuntu 16.04 64bit.

**Comment by Quacky2200** [comment]
Yes I can see this issue too. It's probably the electron app not being quit properly, I'll have a look tomorrow as to the source of the issue (it's 3:13AM). Luckily it doesn't look to be the node processes as I had tons of zombie processes when I was refactoring the controller and D-Bus stuff.

**Comment by JasonLG1979** [comment]
Right on. I know how it is we do this stuff for "fun",lol!!! get to it when you can :)

**Comment by Quacky2200** [comment]
You should have seen the process trying to get the notifications to work properly - pure hell until my tired self had a genius plan to look at the messages being received by the player itself. It was actually such a simple idea I felt I should have been banging my head but I'm just glad it turned out well. 

The Node.js D-Bus stuff was pure hell but when managed correctly seems to be fine.

All in all, it just seems to take time to make everything stable - until it comes to packaging, that's a whole 'nother ball game that is too complicated despite the end result being 'simple'. Hmm...

**Comment by JasonLG1979** [comment]
For me notifications was relativity easy. MPRIS was the huge pain in the Butt. Not one single applet/DE seemed to actually follow the spec to the letter. If you wrote an app with all the MPRIS features that followed spec to the letter you'd end up with at least one thing broken with each applet/DE...

**Comment by Quacky2200** [comment]
It wasn't really the notifications, more over the fact that Spotify's set title and handling of the DOM changes were erratic, the best thing is to get to the source of the track information but at the time the app was making two requests, one from spotify and another from the app itself. Also the app had to get the right URI and the URI was either found in the cover art (that is always late to change) or by play/next/pause events that were not always present. MutatorEvents were used for a brief time to get the URI when the track changed but the DOM was dynamic and the changes weren't always followed up. In the end, it turned out that a simple message listener on the player gives us all the track and player information we need. For example, this is a ton of information that Spotify's Web Player gets each second of playback in one of the messages...

```
{
   "id":2409,
   "success":true,
   "payload":{
      "type":"change",
      "data":{
         "__uid":7,
         "__rules":{
            "skipCount":-1,
            "volume":true,
            "seek":true,
            "indexing":true,
            "previous":true,
            "playpause":true,
            "next":true,
            "shuffle":true,
            "repeat":true,
            "repeatTrack":true
         },
         "playing":false,
         "volume":1,
         "position":4201,
         "duration":174515,
         "track":{
            "uri":"spotify:track:0gBh3OrwSpYrO6AiPqNhLp",
            "playableId":"08cc3cac03c84e98a53533ad0563b3f7",
            "_pid":"08cc3cac03c84e98a53533ad0563b3f7",
            "playableURI":{
               "type":"track",
               "id":"08cc3cac03c84e98a53533ad0563b3f7"
            },
            "name":"Say You Love Me - Alex Adair Remix",
            "disc":1,
            "duration":178647,
            "local":false,
            "number":3,
            "popularity":51,
            "availability":"available",
            "playable":true,
            "starred":false,
            "explicit":false,
            "advertisement":false,
            "fileId":"c1cf31cf34824f90e51a5be39e53368a7c795f21",
            "seen":true,
            "album":{
               "uri":"spotify:album:0RlGIU10VCrWpFNeXK1UKu",
               "name":"Say You Love Me (Remixes)"
            },
            "albumUri":"spotify:album:0RlGIU10VCrWpFNeXK1UKu",
            "albumName":"Say You Love Me (Remixes)",
            "image":"https://d3rt1990lpmkn.cloudfront.net/unbranded/a6bae3c18e9cf2db9bcfcb6f386a1afe74628063",
            "images":[
               [
                  64,
                  "https://d3rt1990lpmkn.cloudfront.net/unbranded/6ffe422eebfe63bd7973dd6653c7241bc31de1f3"
               ],
               [
                  300,
                  "https://d3rt1990lpmkn.cloudfront.net/unbranded/a6bae3c18e9cf2db9bcfcb6f386a1afe74628063"
               ],
               [
                  640,
                  "https://d3rt1990lpmkn.cloudfront.net/unbranded/53195439b3fdf75cb8df612f2036efab2f475229"
               ]
            ],
            "imageLargest":"https://d3rt1990lpmkn.cloudfront.net/unbranded/53195439b3fdf75cb8df612f2036efab2f475229",
            "artists":[
               {
                  "uri":"spotify:artist:5Mq7iqCWBzofK39FBqblNc",
                  "name":"Jessie Ware"
               },
               {
                  "uri":"spotify:artist:2Ys04YPm7sk2GVTQN4IN9L",
                  "name":"Alexander Adair"
               }
            ],
            "artistName":"Jessie Ware, Alexander Adair",
            "previewURI":{
               "type":"audiofile",
               "id":"a58ec0b67548d8f7c7b6f0f42fa9ccc6192af2be",
               "extension":"mp3"
            }
         },
         "__owner":"spotify:app:user:1122005390:2ByecndU8GlMz57huTXIXh",
         "__index":{

         },
         "context":{
            "uri":"spotify:user:1122005390:playlist:2ByecndU8GlMz57huTXIXh"
         },
         "contexts":[
            {
               "descriptor":{
                  "type":"list",
                  "uri":"spotify:user:1122005390:playlist:2ByecndU8GlMz57huTXIXh"
               }
            }
         ],
         "shuffle":true,
         "repeat":0
      },
      "event":"change"
   }
}
```

**Comment by JasonLG1979** [comment]
Aside from where or how you got that info it looks simple enough. Just grab the track title, artist name, album title and cover image and you're golden right?

**Comment by Quacky2200** [comment]
I'm just going to say, it would seem so. Most times it may be simple, other times it needs to be specific because of the way it was developed by the third-party. It's much more efficient to just copy what Spotify's is sending rather than getting the track manually, especially when the notification needs to be almost instant.

Back to the issue, what settings are you using that are stored in `~/.spotifywebplayer/.preferences.json` and how did you close the application (Quit from tray icon, MPRIS controller, close window button, kill process, etc)?

**Comment by JasonLG1979** [comment]
I started with the default settings, whatever they are I don't remember? I fiddled with the settings to see if I could narrow it down and nothing seemed to help.

Here are my current settings:
```js
{"CloseToTray":true,"CloseToController":false,"ShowApplicationMenu":true,"ShowTray":true,"TrayIcon":"lime","Notifications":{"ShowTrackChange":true,"ShowPlaybackPlaying":true,"ShowPlaybackPaused":true,"ShowPlaybackStopped":true,"OnlyWhenFocused":true},"NavBar":{"Follow":false,"User":true,"Radio":true,"YourMusic":true,"Browse":true,"Settings":true,"Search":true,"Sing":false},"AlbumCacheDisabled":true,"Theme":"dark","StartOnLogin":false,"StartHidden":false,"ShowDevTools":false,"lastURL":"https://play.spotify.com/browse"}
```

**Comment by Quacky2200** [comment]
if I close the window the application is still active with the Tray but when quitting the application from the tray, I don't get any zombie processes. I cannot reproduce the problem. Hmm :(

**Comment by JasonLG1979** [comment]
If I close the app to the tray and quit with the tray icon I still get the Zombie.

**Comment by Quacky2200** [comment]
Hold on, I'll try in a VirtualBox environment

**Comment by JasonLG1979** [comment]
I'm running on a real Xubuntu install. I had to install a *buntu to test somethings in Pithos and I thought I'd checkout your app in *buntu.

**Comment by Quacky2200** [comment]
Ok I was able to reproduce in a 64bit Debian installation, perhaps there's a difference between my dev version and the install, I must've changed something so I'll have to investigate haha

**Comment by JasonLG1979** [comment]
> perhaps there's a difference between my dev version and the install

I hate when that happens. I'm not a linear thinker myself. I tend to have several patches in the works at any given time. I sometimes get confused myself as far as what's what,lol!!!

**Comment by Quacky2200** [comment]
Well the biggest problem with app development is always being able to run it fine on a dev install and then having to make sure it works on everything else :) Still have no idea what I've changed LOL!

**Comment by JasonLG1979** [comment]
I'm disabling all options except "Show Application Menu"(which should not be an option if the tray icon is disabled. How would you get to the prefs menu?) to see if I can help narrow it down.

**Comment by JasonLG1979** [comment]
> Still have no idea what I've changed LOL!

You'll have that,lol!!!

**Comment by Quacky2200** [comment]
I think the issue is because of the D-Bus services. They get stopped on a reload but never get stopped when on a tray quit. Simply adding these lines may help fix the issue under `line 42` in `./spotifywebplayer/js/preloaded/tray.js`

```
appMenu.toggleMenu(false);
controller.stopService();
```

**Comment by JasonLG1979** [comment]
I'll try it but I get the issue without the tray icon enabled. Is the tray icon code live even if the icon is not shown/toggled on?

**Comment by Quacky2200** [comment]
Yes that's somewhat a bug that you can't get to the preferences menu but at the moment, people want to be able to hide the tray and application menu, the only way is to edit config file itself and reload the application, I do think it would be best to add some kind of other way on the player itself but not quite sure where, perhaps in the bottom right of the player when both the tray and application menu are missing. 

Also, the tray quit button is live for both the tray and application menu quit button. It could be that I'm missing a window 'on close' event, I'll see to that as well.

**Comment by Quacky2200** [comment]
If you add under `line 160` in `./spotifywebplayer/js/backend/properties.js`

```
mainWindow.on('closed', () => {
    electron.app.quit();
    process.exit(0);
 });
```
You should see the bug disappear? Since after the window is actually closed/disposed, the whole app needs to quit, hopefully it will work.

**Comment by JasonLG1979** [comment]
People want stupid things. Not being able to get to the prefs menu should not happen. Just make the toggle insensitive if the tray icon is disabled. Or just make a keyboard shortcut?

**Comment by JasonLG1979** [comment]
Sometimes you just got to say "No, that just doesn't make sense. I'm not going to do that." When a user complains about something or suggests something that's obviously stupid.

**Comment by Quacky2200** [comment]
Keyboard shortcuts get de-activated when the application menu is turned off, I could swap them to browser events instead so that they are present so, yay, another bug.

I personally like the idea of turning off the application menu, if you look at Gnome, the application menu and a huge header bad makes the application take up too much space. I think I'll keep it, I'll just make sure people can always use shortcuts and still get to the preference window without a shortcut too.

**Comment by JasonLG1979** [comment]
> if you look at Gnome, the application menu and a huge header bad makes the application take up too much space.

If you set the Gtk.HeaderBar to not save space for a subtitle it's normal sized.

**Comment by Quacky2200** [comment]
Sadly I can't do that until Electron supports GTK 3 header bars.

_On another note, I should make a gitter.im convo_

**Comment by JasonLG1979** [comment]
> On another note, I should make a gitter.im convo

for sure.

Neither of the above changes did anything...

**Comment by JasonLG1979** [comment]
When the app starts 2 process named spotifywebplayer are spawned. One has a widow icon by it so I'm assuming that's the window what's the other process? It's the one that  turns into a Zombie.

**Comment by Quacky2200** [comment]
It could be bash?

**Comment by JasonLG1979** [comment]
Why is bash running a GUI app and not disowning it and closing right after it starts?

**Comment by Quacky2200** [comment]
Bash only changes directories and runs electron, it stays active until the electron process quits?

**Comment by JasonLG1979** [comment]
It might not have to? Have you tried command & disown & exit?

**Comment by Quacky2200** [comment]
I had never thought to quit it to be honest, how big is the process? If it were bash, surely it wouldn't take much ram at all?

**Comment by JasonLG1979** [comment]
It's a @43MB on Xubuntu. And it's a Zombie so you get a new one every time you start the app.

**Comment by Quacky2200** [comment]
Yeah I don't think that's bash then. 

_[continue this conversation on gitter.im](https://gitter.im/SWP4L/Lobby#)_

**Comment by Quacky2200** [comment]
@JasonLG1979 Look at this and see if you get the same result:
[gitter.im conversation on 1st October 2016 at 15:31](https://gitter.im/SWP4L/Lobby?at=57efc8b4b0ff456d3ad79839)
