### ISSUE TITLE
elementary os no icon in the system tray

### ISSUE THREAD

**Issue by stibb** [Quacky2200/Spotify-Web-Player-for-Linux#35]
In elementary os does not display an icon in the system tray. Notifications are displayed.

**Comment by Quacky2200** [comment]
Elementary OS Loki removed AppIndicators in their 0.3/4 beta preventing many normal tray icons from being displayed.

You can look at these three pages:
https://github.com/electron/electron/issues/6479
https://github.com/electron/electron/issues/5050
https://github.com/electron/electron/pull/7319

**Comment by Quacky2200** [comment]
Just an update, apparently Electron 1.4.2 fixes the missing icon in Elementary you just need to change the version in the `get_prerequisites.sh` script located in `/usr/bin/spotifywebplayer` and then run the script with `sudo sh /usr/bin/spotifywebplayer/get_prerequisites.sh`

**Comment by stibb** [comment]
Thank you, it works perfectly.
