### ISSUE TITLE
It's unclear how to start spotifywebplayer

### ISSUE THREAD

**Issue by gregghz** [Quacky2200/Spotify-Web-Player-for-Linux#36]
```
➜ pwd
/usr/bin/spotifywebplayer
➜ ls
get_prerequisites.sh  icons  js  libs  LICENSE  main.js  node_modules  node_modules_x64.zip  package.json  plugins  spotifywebplayer
➜ ./spotifywebplayer 
./spotifywebplayer: 2: ./spotifywebplayer: Bad substitution
./spotifywebplayer: 5: ./spotifywebplayer: /usr/bin/spotifywebplayer: Permission denied
➜ cat spotifywebplayer 
#!/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OLDDIR=$(pwd)
cd $DIR
$DIR/libs/electron/spotifywebplayer $DIR/.
cd $OLDDIR%
➜ spotifywebplayer
zsh: permission denied: spotifywebplayer
```

It seems to me that nothing is installed into a default PATH for linux. Regardless, the script that appears to be the launcher (spotifywebplayer) fails to work. It apparently needs additional parameters. I'm not sure what those should be.

This was after installing via the 1.0.0 deb file.

**Comment by Quacky2200** [comment]
run it as a bash script `. /usr/bin/spotifywebplayer/spotifywebplayer` or launch it with a gtk-launch `gtk-launch spotifywebplayer`.
