### ISSUE TITLE
GNOME Desktop integration [feature request]

### ISSUE THREAD

**Issue by AdnanHodzic** [Quacky2200/Spotify-Web-Player-for-Linux#40]
First of all, kudos for this awesome project. 

However, I have couple of feature requests when it comes to GNOME Desktop integration. 

![spotify-web-player-on-gnome-desktop](http://hodzic.org/img/spotify%20web%20player%20-%20gnome%20integration.png)

**1. Ability to hide window menu bar**. Currently there's no way to hide these. For reference you can use Slack which is also built using Electron. Where by pressing "alt" key you will hide the menu bar.

**2. Title bar** doesn't match with GNOME "Dark Theme". Although rest of the windows title bars are black, this is not the case here. Electron supports the [Gtk3 "darkTheme"](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#class-browserwindow) however it seems like by default it's set to "false"

**Comment by Quacky2200** [comment]
You can hide the menu bar in preferences by a setting called 'Show Application Menu' however you can't access the preferences after without either the tray icon or menu bar itself - I am working on this.

Should the dark theme be a setting or should it detect when the dark theme is activated? I know that on GNOME you can set the theme to be dark everywhere in gnome-tweak-tools

**Comment by AdnanHodzic** [comment]
Great, thanks disabling "Show Application Menu" did exactly what I was looking for in point **1. Ability to hide window menu bar**

Regarding **2. Title bar**, turns out that logging out wasn't enough. After reboot, title bar did inherit "dark theme" set in Tweak Tool. 

One more unrelated question. How can I get sound controls working in GNOME? Am I missing some packages or an extension? Because I see on Unity they work out of box.

![spotify-web-player-gnome-volume-controls](http://hodzic.org/img/spotify%20web%20player%20-%20missing%20controls.png)

**Comment by Quacky2200** [comment]
Try this GNOME extension? https://extensions.gnome.org/extension/55/media-player-indicator/

**Comment by AdnanHodzic** [comment]
Worked perfectly! 

Thank you so much and keep up the great work!
