### ISSUE TITLE
Electron dependency issue?

### ISSUE THREAD

**Issue by szekeres2016** [Quacky2200/Spotify-Web-Player-for-Linux#43]
Hi, I've tried to install it on my new laptop, it seems to be working at first since there is no error message with GDebi, but the application fails to start. After installing it with dkpg -i command it seems to be some sort of missing dependency thing going on, could you please look into this? Thank you!

![kepernyokep 2016-10-19 10-23-46](https://cloud.githubusercontent.com/assets/20751590/19511166/6948b660-95e6-11e6-8788-af1dda30adef.png)

**Comment by Quacky2200** [comment]
have you tried sudo apt install -f ? It should make sure to install dependencies

**Comment by szekeres2016** [comment]
Tried it just now, found no missing dependency.

**Comment by Quacky2200** [comment]
what output do you get when you launch it with `gtk-launch spotifywebplayer`?

**Comment by szekeres2016** [comment]
/usr/bin/spotifywebplayer/spotifywebplayer: sor: 5: /usr/bin/spotifywebplayer/libs/electron/spotifywebplayer: Nincs ilyen fájl vagy könyvtár

In English: No file or library...

**Comment by Quacky2200** [comment]
Also, from your screenshot, it looks as if Electron was never fully downloaded (2%?), I would make sure to run the post install script again with `sh /usr/bin/spotifywebplayer/get_prerequisites.sh`

**Comment by szekeres2016** [comment]
Yes that must be it, but it stops at 2%.. can it be a server error or something like that?

**Comment by Quacky2200** [comment]
Not sure, your screenshot looks like it says 'segmentation fault' under the download? I'm not sure what would cause that for a simple download...

**Comment by Quacky2200** [comment]
You could try download the Electron file manually and try to extract it to the `/usr/bin/spotifywebplayer/libs/electron` directory, you'd have to rename the Electron executable to `spotifywebplayer`. 

[Electron v1.4.2 64 bit direct download](https://github.com/electron/electron/releases/download/v1.4.2/electron-v1.4.2-linux-x64.zip)

**Comment by szekeres2016** [comment]
Hmm didn't work, there could be something wrong with the system. I've installed through Wi-Fi and there are other strange things happening as well (some corrupted package perhaps...), will reinstall through Ethernet cable today. Will give an update if the issue persists. Thanks for ideas though! :)

**Comment by szekeres2016** [comment]
Alright, problem solved, something funny must have been going on with previous installation because now it installed perfectly and no other system anomalies. Sorry to bother you with this, I'm glad it works though. :)
