### ISSUE TITLE
Flash player not installed

### ISSUE THREAD

**Issue by maicolcampos** [Quacky2200/Spotify-Web-Player-for-Linux#44]
Hi, im using Elementary os loki, and i have installed chrome, opera and firefox, all this  browsers have flash plugin running with no problem. the only i couldnt make run flash player it's chromium.
And the spotify-web-player too.

**Comment by Quacky2200** [comment]
A few quick questions:
 - You installed the 64 bit version?
 - The file `libpepflashplayer-x64.so` is present in `/usr/bin/spotifywebplayer/plugins`?

**Comment by Quacky2200** [comment]
Closing due to lack of communication for 14 days
