### ISSUE TITLE
Add non-media keyboard shortcuts?

### ISSUE THREAD

**Issue by jonasws** [Quacky2200/Spotify-Web-Player-for-Linux#45]
It would be great if one could use modifier keys to control the player, like such:

* Play/pause: `Space`
* Previous: `Ctrl-Left`
* Next: `Ctrl-Right`

Is this possible to achieve (any GNOME tricks I should know about?)

**Comment by Quacky2200** [comment]
At the moment the only key modifiers (shortcuts) for playback are the media buttons. You could use GNOME's keyboard assignment to change it around or add different keys with manual D-Bus commands. However Ctrl-Right and Ctrl-Left are both used for general text input (change caret position per word), and as such; I don't believe they should be assigned for this use case.

You can press space to play/pause when the player is in focus.
