### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by nzurita** [Quacky2200/Spotify-Web-Player-for-Linux#47]
Hello, due to a [bug in Ubuntu 16.04](http://askubuntu.com/questions/760638/problem-with-deb-packages-on-ubuntu-16-04) I can't install deb package, so I tryed different methods for install.

If I follow [manual installation](https://github.com/Quacky2200/Spotify-Web-Player-for-Linux#manual-install) steps and then I do `bash /usr/bin/spotifywebplayer/spotifywebplayer` I get error `/libs/electron/spotifywebplayer not found`:

> /usr/bin/spotifywebplayer/spotifywebplayer: línea 5: /usr/bin/spotifywebplayer/libs/electron/spotifywebplayer: No existe el archivo o el directorio

Also, is there a way to get an application icon and launch from unity dash?

Thank you

**Comment by Quacky2200** [comment]
I find that `dpkg` and `gdebi` work rather than `apt-get` or the software center. Have you tried those? Have you tried `apt install -f` to see if any new packages need to be installed?

With the manual install you need to run the `get_prerequisites.sh` script

**Comment by Quacky2200** [comment]
I am closing this due to the lack of communication of a period of 6 days.

**Comment by nzurita** [comment]
Sorry @Quacky2200, you're right, too busy these days :-), I'll try again in a few days and report results

**Comment by Quacky2200** [comment]
That's fine, reopen when you get time. A few people tend to leave them so I close them after a little while assuming they either fixed it or could never be bothered. No worries
