### ISSUE TITLE
Releases are looking weird :D

### ISSUE THREAD

**Issue by GinoHereIam** [Quacky2200/Spotify-Web-Player-for-Linux#48]
Hi,

the releases are looking weird on my Fedora 25.
![bildschirmfoto von 2016-11-08 22-24-55](https://cloud.githubusercontent.com/assets/3085830/20117791/593834e0-a602-11e6-840a-9c69861f031e.png)

Regards
Gino

**Comment by Quacky2200** [comment]
Yes this is currently a problem with different adverts, I'm looking into changing this for the next release
