### ISSUE TITLE
I can't logout

### ISSUE THREAD

**Issue by leoheck** [Quacky2200/Spotify-Web-Player-for-Linux#50]
Hi, someone can help me with that? Using version 1.0.0

**Comment by Quacky2200** [comment]
Since the Facebook login has always been hard to keep track of cookies and redirections, I have found it hard to login, naturally, I felt it was better to remove all cache for a logout function whilst the website logs you out. 

Do you have the settings button at the bottom left to logout? You can logout at the bottom of that page. Otherwise there's an application menu for logging out, as well as the Tray menu (if memory serves me correctly)

**Comment by leoheck** [comment]
I have discovered that I have 2 accounts (wtf?), one within facebook and another without it. What happens is that I am premium without facebook, and this account is one that I have used to login with this client. 

So, I am trying to change the accounts. But I can't! 
I have tried your 2 suggestions to logout but nothing happens.

I tried to purge it (using .deb version) and installing it again but the credential was kept safe, so I was unlucky now.

Probably if I delete the user files it enable to login again, what is your suggestions?
I may try  to login the web version in browser to hit "logout all clients" this can help.

**Comment by leoheck** [comment]
This have worked: ``rm -rf ~/.spotifywebplayer``

**Comment by Quacky2200** [comment]
Yes you can literally just delete the whole `.spotifywebplayer` found in your home folder...

Ok, you just found it...

**Comment by Quacky2200** [comment]
As it has been very hard for you to logout, I think I will look into sorting this out for the next version as it's unnatural to delete the whole folder to logout.

**Comment by leoheck** [comment]
Yeah, I think this feature will be nice to have! Thanks for this app by the way. Should I close the issue or we will keep it open for the next version?

**Comment by Quacky2200** [comment]
Let's keep it open until I can find out if I can duplicate and/or fix :)

**Comment by Quacky2200** [comment]
I was wondering if you could test this in the new version released? I never had the problem when I had two accounts but that was whilst I was developing v1.0.0. AppImage is fine if you don't want to install a new version right away

**Comment by leoheck** [comment]
Ok, testing v1.0.25. My first attempt to log out just closed the app and when I open it again, the account remained active. The second attempt has worked, the app didn't close going to the login screen.

**Comment by Quacky2200** [comment]
Hmm, I thought I'd try and it didn't work at all. I found out that I never refactored the user logout was using old code. It was fixed in 7372c557ffab2dcf22dfdc50ca3143dc1bbf241b
