### ISSUE TITLE
DBus implementation without node

### ISSUE THREAD

**Issue by vincent-t** [Quacky2200/Spotify-Web-Player-for-Linux#52]
Why does DBus need node? As far as I understand this implementation doesn't need node: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/tree/d40f511531e2966f9aa2917201a6cf6a9a7ff7a6/src/main/features/linux.

**Comment by Quacky2200** [comment]
I tried it many times before and never got it working successfully due to some kind of error from libnode.so and different bindings, it could be setup issue on my part. At the moment I have not been able to get back into development due my hectic life right now :/

**Comment by Quacky2200** [comment]
I've been developing a solution to this problem recently fixed in ae0d7fda17aae4253429109bbae442142083a5c6
