### ISSUE TITLE
Spotify web player update has broken app

### ISSUE THREAD

**Issue by Plasmodium1** [Quacky2200/Spotify-Web-Player-for-Linux#53]
It seems an update to Spotify's web player has broken your app.

When I start it, I just get a "Log in with Spotify" page. When I click the button, a small window flashes up but disappears before I can see what it is, returning me to the "Log in with Spotify" page.

Opening play.spotify.com in my browser reveals a largely overhauled UI, which indicates to me that Spotify may have changed something pretty big on their end.

**Comment by Quacky2200** [comment]
Which update are you referring to and which version are you running? v1.0.0 has quite a few problems, especially logging in and the lyric system. I currently cannot do much with development right now. 

It might be best to delete everything in ~/.spotifywebplayer except for `preferences.json`, and the album and lyric cache folders

**Comment by Plasmodium1** [comment]
How do I tell which version I am using?

By update I meant an update from Spotify's side, not yours.

Deleting those folders took me to a login page I could use, but logging in through that just redirected me back to the same "Log in with Spotify" page.

**Comment by Quacky2200** [comment]
Ok sorry, I see no update on my side with Spotify, perhaps my account isn't affected.

Are you seeing this type of interface at all? https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/quot-play-quot-site-webplayer-redirecting-to-quot-open-quot-site/td-p/1514471

**Comment by Plasmodium1** [comment]
Maybe they are rolling out account by account? Interesting.

That link does describe what happens. When I go to "play.spotify.com" in my browser (Chrome) I am in fact redirected to "open.spotify.com". I hadn't noticed that before - I assumed it was just a redesign to "play.spotify.com".

Here is a screenshot of what I see when I open your app:
![image](https://cloud.githubusercontent.com/assets/11717287/20846622/75ce4e82-b8c2-11e6-899f-df598c08cd72.png)

Clicking the green button does nothing - except for flashing up a small window which disappears before I can read it.

If I clear out the caches as you suggested, I get this; (with my username blurred out!):
![selection_004](https://cloud.githubusercontent.com/assets/11717287/20846667/abc2b5d2-b8c2-11e6-9a28-5f674fcf10ff.png)

Logging in via the "Already have an account..." just takes me back to the screen in the first screenshot.

I appreciate that if these are changes on Spotify's side, there's not much you can do! Thanks for your development on the app so far, though! It's been really good up till Spotify (seem to have) shafted you...

**Comment by Quacky2200** [comment]
I have a feeling this may have been an update in a specific region because open.spotify.com always redirects to play.spotify.com for me without having any cache trying to play an album by a URL, whereas for you, it always redirects to open.spotify.com. This must be the newer version they're pushing out to people, most probably in the USA/Canada region

**Comment by Plasmodium1** [comment]
That would be my guess as well, though I'm in the UK, so it may not be geographically based. Who knows...

**Comment by Quacky2200** [comment]
Unless you live in London, who knows o.0

**Comment by Quacky2200** [comment]
Are you using a Facebook integrated account or a Spotify account?

**Comment by Plasmodium1** [comment]
I originally signed up via the Spotify page and never connected my Facebook account, so the latter I assume!

**Comment by Quacky2200** [comment]
Should have added this to the above question alas...When did you sign up? and what age range are you? under 25, 25 - 35, 35+. Are you a premium user? Do you use any VPNs that may change your geolocation?

**Comment by Plasmodium1** [comment]
I signed up in about Nov 2012, and I am under 25.

I am a premium user on and off. For example, currently I have premium as there was a good deal in Dec, and likewise, over the summer I had it for 3 months. FWIW, I did not have premium when I started seeing these UI changes/inability to log in.

I do not use any VPNs etc to change my location.

**Comment by Quacky2200** [comment]
I have a feeling it must be premium that has given you faster access to the new UI despite not having premium when the UI changed. I had two accounts; one with Facebook (once had premium for half a year) and my Spotify account that never saw the likes of premium and I used to see more UI changes with my integrated Facebook account than I ever did with my Spotify account. 

I think that means I may have to make another account with premium to try and duplicate the issue but I'm not exactly keen on paying for a membership right now unless I get a good deal :smile:

**Comment by Plasmodium1** [comment]
Ok. I understand that there is not much you can do until you see the new UI! I second what you say about not buying unless there is a good deal. Plus in this case, we are not 100% sure that you will necessarily see the new UI immediately if you buy premium!

**Comment by stianst** [comment]
@Quacky2200 maybe worth sending an email to the Spotify guys? They should give you a premium account for free for your efforts. The fact that they no longer support Linux folks is beyond shitty and you have really saved the day with your app! Awesome job by the way.

**Comment by Quacky2200** [comment]
Thanks but I honestly don't think they'd see it that way right now considering they released their latest UI around the release of v1.0.0 - Although now you mention it, I think maybe a premium account would be nice 👍

**Comment by ssantana92** [comment]
I'm experiencing the same thing described here, also detailed at issue #67.

I don't think I have ever associated my facebook account with spotify.
Finally, [here's a screencast showing what happens](https://youtu.be/9Qgx19inXC0).

**Comment by ilopmar** [comment]
This happen to my this morning. I was a premium user long time ago and now I have the new web interface and the app is not working.

In the chrome-console I can see the error:

```
Uncaught TypeError: Cannot read property 'contentWindow' of null   (program:3)
```

**Comment by Quacky2200** [comment]
@ilopmar, sorry abut the lack of a reply, I never got a notification about this. However one thing I will say now is that I'm getting the new interface and so I will be developing the next version soon to fix this issue

**Comment by Plasmodium1** [comment]
I'm glad to hear you are working on a fix! I much prefer your app to the official one as it allows the use of media keys. Good luck with the development!

**Comment by Quacky2200** [comment]
Okay, I'm not one who likes to give bad news but this new version of their inteface is the basically the end-all of the application. 

If you'd like to read more, please refer to my [discontinuation of Spotify Web Player for Linux](http://mattjames.co.nf/journal/spotify-web-player-discontinued).

I would like to apologise to anyone who feels disappointed about this decision, it was one that took a lot to think about. It's sadly what happens when you rely on a third party in all honesty.

**Comment by Plasmodium1** [comment]
I'm sorry to hear that. But I realise it's not your fault. Thanks for all your dedication to maintaining this app so far.

**Comment by ilopmar** [comment]
This is really bad news :-(. It's not your fault, but Spotify.

Thank you very much for all your hard work!

**Comment by Quacky2200** [comment]
A new fix for anyone who may want to continue to use my application has been applied in commit b325d4c391f9d1e8749b71c16290433837625173. A new release will be available ASAP.
