### ISSUE TITLE
flash

### ISSUE THREAD

**Issue by xxcriticxx** [Quacky2200/Spotify-Web-Player-for-Linux#57]
@Quacky2200 ver 1.0.0 tell me to enable flash constantly even though flash is already enable on this system

**Comment by Quacky2200** [comment]
Sorry about the delay. Have you seen the related issues #44 and #6? Perhaps these could help?

**Comment by xxcriticxx** [comment]
@Quacky2200 #44 is dead and i will try #6 when i get home today

**Comment by xxcriticxx** [comment]
ok i fixed my problem i installed 32bit ver on 64bit system
