### ISSUE TITLE
developer tools

### ISSUE THREAD

**Issue by xxcriticxx** [Quacky2200/Spotify-Web-Player-for-Linux#59]
@Quacky2200 can you please enable developer tools so we can check console for errors?

**Comment by Quacky2200** [comment]
If you go into preferences you can enable dev tools

**Comment by xxcriticxx** [comment]
after enable pressing ctrl+shift+i dont work

**Comment by Quacky2200** [comment]
Yeah that functionality isn't present, the dev tools only open when the window is initialised

**Comment by xxcriticxx** [comment]
should we drop errors here?

**Comment by Quacky2200** [comment]
Up to you, we can always change the title if required

**Comment by xxcriticxx** [comment]
@Quacky2200 check this out http://pastebin.com/x684Peht

**Comment by Quacky2200** [comment]
I wouldn't worry, none of those errors actually affect you. It's just Spotify checking for their own hosts. I can only guess that it's searching for different hosts/ports to be able to connect to without actually error checking. Also, the FB error and the unsafe http requests are part of Spotify's actual website too.

**Comment by xxcriticxx** [comment]
got it cant wait for next version

**Comment by Quacky2200** [comment]
The new version will have the Ctrl-Shift-I shortcut - if you use the sound menu I would wait for the v1.0.30 release coming later today/tomorrow since it has a small annoying bug but if you wish you can still update to v1.0.25 in the meanwhile.
