### ISSUE TITLE
Spotify dialog claims need to install Adobe Flash

### ISSUE THREAD

**Issue by nicholas-gh** [Quacky2200/Spotify-Web-Player-for-Linux#6]
I used https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/download/v0.8.19/spotifywebplayer_amd64-fixed.deb

I'm using Debian, 64bit.

I see  `/usr/bin/spotifywebplayer/plugins/PepperFlash/libpepflashplayer.so` does exist.

I also see it being read:

```
$ strace -ff /usr/bin/spotifywebplayer/lib/electron/electron . 2>&1 | grep plugins
[pid 10444] access("/usr/bin/spotifywebplayer/plugins/widevinecdmadapter.so", F_OK <unfinished ...>
[pid 10513] open("/usr/bin/spotifywebplayer/plugins/PepperFlash/libpepflashplayer.so", O_RDONLY|O_CLOEXEC) = 21
[pid 10513] access("/usr/bin/spotifywebplayer/plugins/PepperFlash/libpepflashplayer.so", F_OK) = 0
```

However, the Spotify 'site' in the Electron window claims I need to install Flash.

I upgraded the bundled `libpepflashplayer.so` like this:

```
sudo /usr/sbin/update-pepperflashplugin-nonfree --install --verbose
sudo cp /usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so /usr/lib/pepperflashplugin-nonfree/manifest.json /usr/lib/pepperflashplugin-nonfree/pubkey-google.txt plugins/PepperFlash/ -va
```

The output of `update-pepperflashplugin-nonfree` tells me this is version **22.0.0.209**

Spotify now works in the Electron window.

**Comment by Quacky2200** [comment]
Sadly I never got round to properly testing the 64 bit version as I'm only only 32bit - I assumed the flash should work fine with electron withstanding any 32-64bit changes. 

The only thing I would have asked is to just chmod it to 777 as it could have just been a permission error somehow?

I will lookup into it and see if I can recreate the issue but for now hopefully you're still able to use Spotify without issue

**Comment by Quacky2200** [comment]
Okay, I've had a look, turns out the 64bit version uses a different pepperflash, sorry about that, I thought it wasn't affected by the architecture changes. Doh!

I have updated the releases page with the new version and it has been tested, it's up to you whether you want to update to it or not. :)

https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/tag/v0.8.19
