### ISSUE TITLE
Arch Linux packages

### ISSUE THREAD

**Issue by twa022** [Quacky2200/Spotify-Web-Player-for-Linux#62]
I created packages for Arch Linux in the AUR.
stable: [https://aur.archlinux.org/packages/spotify-web-player/](https://aur.archlinux.org/packages/spotify-web-player/)
development: [https://aur.archlinux.org/packages/spotify-web-player-git/](https://aur.archlinux.org/packages/spotify-web-player-git/)

Could you add links in the install section?

Thanks.

**Comment by Quacky2200** [comment]
Sure, glad to see some Arch activity :+1: I would love to distro-hop to Arch again sometime in the future but maybe when I have lots of free time to set everything up :smile:

**Comment by TamasBarta** [comment]
@twa022 the packages disappeared from the AUR. What happened to them? Are you planning to put them on again?

**Comment by Quacky2200** [comment]
Hi @TamasBarta,

Spotify Web Player for Linux is discontinued. It's probably no surprise that the AUR maintainer decided to remove this.

**Comment by TamasBarta** [comment]
@Quacky2200 thanks, I overlooked it. I only checked the project description, not the README.
