### ISSUE TITLE
Native buttons to control playback don't work

### ISSUE THREAD

**Issue by ilopmar** [Quacky2200/Spotify-Web-Player-for-Linux#7]
I've installed the latest version on Linux Mint 18 and it's working properly. I've tried to assign some keyboard shortcuts to play/pause a song, play next song, play previous song,... but when I click on my shortcut the action is not executed.

**Comment by Quacky2200** [comment]
If this is using dbus-send, this currently isn't implemented. I had put in the functionality but something happened with mrpis-service for node, so until I figure out a way to develop MPRIS/DBus there will not be any way to control it externally. 

I have looked into global shortcuts as part of Electron but these do not get assigned under Linux as they are already assigned with Gnome/Unity - probably as part of MPRIS control.

I hope this helps to your confusion?

**Comment by ilopmar** [comment]
Thanks for the fast reply.

I don't know if it's using dbus-send or mrpis but now I understand why it's not working.

Thanks!

**Comment by Quacky2200** [comment]
As of currently it doesn't use either, but I intend to add it in a future release

**Comment by Quacky2200** [comment]
I have added B-Dus/MPRIS control, can you tell me whether this improves the functionality you wanted?

**Comment by ilopmar** [comment]
Have you created a new 64 bit `.deb` package? If you create a new one (even if it's not final and only for tests) I can try it.

**Comment by Quacky2200** [comment]
Sure I can try making one for you

**Comment by Quacky2200** [comment]
https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/tag/0.9.4

**Comment by ilopmar** [comment]
It works like a charm! I've assigned keyboard shortcuts to:
- Next song
- Previous song
- Play/Pause

And everything is working as expected.

I've also tested the notifications and now the only appear once. When I change the song the same notification is re-used.

Thank you very much! :+1:

**Comment by Quacky2200** [comment]
That's awesome to hear, I'm glad it works for you. :+1: 

I find the notifications a tiny bit buggy (same instance so they take a small time to update) and D-Bus must uses a separate process with Node.JS so if the notifications stop working you may have to kill all spotifywebplayer/node processes but we'll cross that path if it comes to it - it's the most stable one I can make so far...despite the major bugs I had to deal with :)

**Comment by ilopmar** [comment]
I'm always listening Spotify while working so this next week I'll use it most of the day and let you now if there's some problem with the notifications.
