### ISSUE TITLE
Application does not work anymore

### ISSUE THREAD

**Issue by quentinus95** [Quacky2200/Spotify-Web-Player-for-Linux#71]
@Quacky2200 

Spotify have updated their web app. Login function doesn't work any more.

![image](https://cloud.githubusercontent.com/assets/8060564/22602601/38303276-ea44-11e6-86cb-69c4ecfd9c07.png)

The new login pages opens a popup that is instantly closed.

**Comment by Quacky2200** [comment]
Duplicate of https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/issues/53

**Comment by Quacky2200** [comment]
Spotify are sadly updating users to the new interface slowly, I am unable to help provide a fix or try and debug until they "upgrade" my account. The new updates are not perceived by others on the Spotify Community forum as very welcoming. How long ago did you register with Spotify and are/were you a premium user? I wonder how they are selecting these people to be 'upgraded'. I said this with my application once (can't remember where but pretty sure it was the README.md file a while back) and I said that the application will turn into catch-up development (supplying patches after patches - cat and mouse) which will eventually turn the app useless which is what is slowly-but-surely happening unfortunately.

**Comment by quentinus95** [comment]
Sorry for duplicating another issue.

I'm not a premium user and I have an account since 2 years if I remember well.

I may reset and share my account details with you if it comply with Spotify terms of use, if you want to be able to test and fix the app container.

Thanks anyway!

**Comment by Quacky2200** [comment]
Thanks for the offer but it is pretty much against any terms of service for any user account/service. I wouldn't worry - I think I can wait for now as I can't imagine it taking that long but who knows with spotify -_-. 

If you are able to get into programming with Node.js and understand my code, it could be something you may feel interested in trying for fun, trying to debug but it's really something you should only do if you feel interested :smile: 

Don't worry about creating a duplicate - it happens. :+1:

**Comment by quentinus95** [comment]
I'm always interested in any computing challenge but I sadly do not really have time to do everything I would like to do.

Thanks for your quick answers, I will switch to SoundCloud until the next update arrives!

**Comment by Quacky2200** [comment]
I understand, Thanks for filing the issue, I get the same way with time so it's not a problem.

**Comment by Quacky2200** [comment]
A new fix for anyone who may want to continue to use my application has been applied in commit b325d4c391f9d1e8749b71c16290433837625173 and [release v1.0.42](https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/tag/1.0.42)

**Comment by quentinus95** [comment]
Thanks, the issue is fxed :smiley:
