### ISSUE TITLE
Media hotkeys only work if application window open

### ISSUE THREAD

**Issue by orschiro** [Quacky2200/Spotify-Web-Player-for-Linux#82]
Dear all,

Thank you for your great work on this player!

I have a question: 

I am using the latest release on Ubuntu 16.10. 

However, my media hotkeys (e.g. Fn + F11 to play/pause) only work if the application window is open and has focus. 

Can someone confirm that these hotkeys don't work if the application is minimised to tray?

Yours,

Robert

**Comment by orschiro** [comment]
Moreover, I noticed that I cannot pause/play using the following button:

![image](https://cloud.githubusercontent.com/assets/170947/23994258/6629f188-0a44-11e7-985a-1e02845b70f1.png)

**Comment by Quacky2200** [comment]
Yes, I typically use the media keys. Nothing has changed. I'll let you know if I discover anything

**Comment by orschiro** [comment]
Thank you! :+1:

**Comment by Quacky2200** [comment]
What are your play, previous and next buttons set to under `org.gnome.settings-daemon.plugins.media-keys`?

These should be set to 
`pause` to `XF86AudioPause`
`play` to  `XF86AudioPlay`
`previous` to `XF86AudioPrev`
`next` to `XF86AudioNext`
`stop` to `XF86AudioStop`

**Comment by orschiro** [comment]
Dear @Quacky2200,

I switched to using [playerctl](https://github.com/acrisci/playerctl) mapped to my media keys. Now, as long as I keep the main window of Spotify open, I can toggle the playback using my media keys. 

Let us consider this issue as solved for now. :-)

Thank you for all your help!

Yours,

Robert
