### ISSUE TITLE
Error: Cannot find module 'userhome'

### ISSUE THREAD

**Issue by jarvelov** [Quacky2200/Spotify-Web-Player-for-Linux#9]
This error occurs both with the master branch and the 0.8.19 release. Looking at ```main.js``` there is clearly a ```require('userhome')``` at the top of the file. Just installing userhome with ```npm install userhome``` solves the problem, however this should be included in the release.

Running Arch Linux x64.

**Comment by Quacky2200** [comment]
I see the issue yes, I had removed userhome from the npm module directory by accident when I was releasing it. The 64bit version on the 0.8.19 release shouldn't have this issue?

I am removing the userhome library as it only contains one line of code, pretty useless library to be honest.

**Comment by jarvelov** [comment]
Sorry, should have mentioned that this was occurring when using the 32-bit build of electron.

**Comment by Quacky2200** [comment]
No worries, I never updated the 32bit when the 64bit flash issue arrived, at that point I had remove 'userhome'.

I have uploaded a fixed 32bit .deb on the releases page and linked it below. If you could try this it would help me out as I'm quite busy and if it works I can just replace the old release .deb. You seem to know about npm/electron so this should be easy to test and make sure it would work without userhome/your previous install perhaps?

https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/releases/download/v0.8.19/spotifywebplayerx86-experimental-fix.deb

**Comment by jarvelov** [comment]
Sure, I can help you test that. However, I don't have dpkg so unfortunately I can't install that .deb package. Mind creating a tar.gz of the source with the fix instead?

**Comment by Quacky2200** [comment]
[spotifywebplayer-userhome-fix.tar.gz](https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/files/444984/spotifywebplayer-userhome-fix.tar.gz)
I do not use any type of make-file so you will have to just copy this to the /usr/bin/spotifywebplayer directory.

**Comment by jarvelov** [comment]
I've tested it and can confirm that it works without the ```userhome``` module. Thanks for the quick response. Hope to see it in the next official release.

**Comment by Quacky2200** [comment]
I'll change the releases. Thanks for testing :) :+1:
